# configmaps
allowEmptyConfigMap: true
configAutoscaler: {}
configDefaults: {}
configDeployment: {}
# configDeployment:
#   queueSidecarImage: gcr.io/knative-releases/knative.dev/serving/cmd/queue@sha256:9b8dad0630029dfcab124e6b4fa7c8e39b453249f0b31282c48e008bfc16faa3
configFeatures: {}
configGc: {}
configLeaderElection: {}
configLogging: {}
configObservability:
  logging.enable-var-log-collection: "true"
  logging.request-log-template: '{"httpRequest": {"requestMethod": "{{.Request.Method}}", "requestUrl": "{{js .Request.RequestURI}}", "requestSize": "{{.Request.ContentLength}}", "status": {{.Response.Code}}, "responseSize": "{{.Response.Size}}", "userAgent": "{{js .Request.UserAgent}}", "remoteIp": "{{js .Request.RemoteAddr}}", "serverIp": "{{.Revision.PodIP}}", "referer": "{{js .Request.Referer}}", "latency": "{{.Response.Latency}}s", "protocol": "{{.Request.Proto}}"}, "traceId": "{{index .Request.Header "X-B3-Traceid"}}"}'
  logging.enable-request-log: "true"
  logging.enable-probe-request-log: "true"
  profiling.enable: "true"
configTracing: {}
zone:
  name:

# secrets
allowEmptySecret: true
servingCertsCtrlCa: {}
knativeServingCerts: {}
domainmappingWebhookCerts: {}
webhookCerts: {}
