{{- if .Values.domainmappingWebhookCerts -}}
apiVersion: v1
kind: Secret
metadata:
  name: domainmapping-webhook-certs
  labels:
    app.kubernetes.io/component: domain-mapping
    app.kubernetes.io/name: knative-serving
data:
  {{- toYaml .Values.domainmappingWebhookCerts | nindent 2 }}
{{- end -}}
