{{- if or .Values.knativeServingCerts .Values.allowEmptySecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: knative-serving-certs
  labels:
    serving-certs-ctrl: "data-plane"
    networking.internal.knative.dev/certificate-uid: "serving-certs"
data:
  {{- toYaml .Values.knativeServingCerts | nindent 2 }}
{{- end -}}
