{{- if or .Values.webhookCerts .Values.allowEmptySecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: webhook-certs
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/name: knative-serving
data:
  {{- toYaml .Values.webhookCerts | nindent 2 }}
{{- end -}}
