kind: ContourDeployment
apiVersion: projectcontour.io/v1alpha1
metadata:
  name: {{ .Values.grpcWeb.gateway.class }}
  namespace: {{ .Release.Namespace }}
spec:
  envoy:
    workloadType: Deployment
    networkPublishing:
      type: LoadBalancerService
      serviceAnnotations:
        service.beta.kubernetes.io/aws-load-balancer-type: external
        service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
        service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "GatewayClass={{ .Values.grpcWeb.gateway.class }},ClusterName={{ required "Chart cannot be installed without a valid clusterName!" .Values.clusterName }}"
        service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
        service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
---
kind: GatewayClass
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: {{ .Values.grpcWeb.gateway.class }}
spec:
  controllerName: projectcontour.io/projectcontour/contour
  parametersRef:
    kind: ContourDeployment
    group: projectcontour.io
    name: {{ .Values.grpcWeb.gateway.class }}
    namespace: {{ .Release.Namespace }}
---
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: {{ .Values.grpcWeb.gateway.name }}
  namespace: {{ .Release.Namespace }}
spec:
  gatewayClassName: {{ .Values.grpcWeb.gateway.class }}
  listeners:
    - name: {{ .Values.grpcWeb.gateway.httpListener.name }}
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
---
apiVersion: operator.projectcontour.io/v1alpha1
kind: Contour
metadata:
  name: {{ .Values.grpcWeb.gateway.name }}
  namespace: {{ .Release.Namespace }}
spec:
  networkPublishing:
    envoy:
      type: ClusterIPService
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: kourier-gateway
  namespace: knative-serving
spec:
  parentRefs:
    - name: {{ .Values.grpcWeb.gateway.name }}
      namespace: {{ .Release.Namespace }}
      sectionName: {{ .Values.grpcWeb.gateway.httpListener.name }}
  rules:
    - matches:
        - path:
            type: Exact
            value: /
      backendRefs:
        - name: kourier-internal
          namespace: knative-serving
          port: 80
