# https://knative.dev/docs/serving/using-a-custom-domain/#configuring-the-default-domain-for-all-knative-services-on-a-cluster
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-domain
  namespace: knative-serving
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/version: 1.6.0
data:
  127.0.0.1.sslip.io: ''
