{{- if .Values.zone.name -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-domain
  labels:
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/component: controller
data:
  {{ .Values.zone.name }}: ''
{{- end -}}
