{{- if .Values.configDefaults -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-defaults
  labels:
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/component: controller
data:
  {{- toYaml .Values.configDefaults | nindent 2 }}
{{- end -}}
