{{- if or .Values.configDomain .Values.allowEmptyConfigMap -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-domain
  labels:
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/component: controller
data:
  {{- toYaml .Values.configDomain | nindent 2 }}
{{- end -}}
