apiVersion: v1
kind: ConfigMap
metadata:
  name: config-network
  namespace: knative-serving
data:
  ingress.class: gateway-api.ingress.networking.knative.dev
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-domain
  namespace: knative-serving
data:
  {{ .Values.zone.name }}: ''
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-gateway
  namespace: knative-serving
data:
  visibility: |
    ExternalIP:
      class: {{ .Values.external.namespace }}
      gateway: {{ .Values.external.namespace }}/{{ .Values.external.gateway.name }}
      service: {{ .Values.external.namespace }}/{{ .Values.external.service.name }}
    ClusterLocal:
      class: {{ .Values.internal.namespace }}
      gateway: {{ .Values.internal.namespace }}/{{ .Values.internal.gateway.name }}
      service: {{ .Values.internal.namespace }}/{{ .Values.internal.service.name }}
