kind: GatewayClass
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: {{ .Values.internal.gateway.class }}
spec:
  controllerName: projectcontour.io/gateway-controller
  parametersRef:
    kind: ContourDeployment
    group: projectcontour.io
    name: {{ .Values.internal.gateway.class }}
    namespace: projectcontour
---
kind: ContourDeployment
apiVersion: projectcontour.io/v1alpha1
metadata:
  namespace: projectcontour
  name: {{ .Values.internal.gateway.class }}
spec:
  envoy:
    networkPublishing:
      type: ClusterIPService
